"""Generate XLSX Test Case untuk Arteri E-Learning (Stuudi)."""
import os
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

OUTPUT = "/home/ubuntu/testing-hub/projects/arteri-elearning/test-cases.xlsx"

# Styling
HEADER_FONT = Font(name="Arial", size=11, bold=True, color="FFFFFF")
HEADER_FILL = PatternFill("solid", fgColor="1E40AF")
HEADER_ALIGN = Alignment(horizontal="center", vertical="center", wrap_text=True)
DATA_FONT = Font(name="Arial", size=10)
DATA_ALIGN = Alignment(vertical="top", wrap_text=True)
PRIORITY_HIGH = PatternFill("solid", fgColor="FECACA")
PRIORITY_MED = PatternFill("solid", fgColor="FED7AA")
PRIORITY_LOW = PatternFill("solid", fgColor="DCFCE7")
THIN = Side(border_style="thin", color="CBD5E1")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

# Format: (ID, Modul, Tipe, Item, Test Case, Pre-condition, Steps, Expected, Priority)
TEST_CASES = [
    # Section A: Authentication & Authorization
    ("AUTH-001", "Auth", "UI/Functional", "Login Form",
     "Login student dengan kredensial valid",
     "User student terdaftar",
     "1. Buka /login\n2. Isi email valid\n3. Isi password valid\n4. Klik Masuk",
     "Login berhasil, JWT disimpan di cookie + localStorage, redirect ke /dashboard",
     "High"),
    ("AUTH-002", "Auth", "UI/Functional", "Login Form",
     "Login teacher dengan kredensial valid",
     "User teacher/admin terdaftar",
     "1. Buka /login\n2. Login sebagai teacher",
     "Login berhasil, redirect ke /dashboard-admin (role-based redirect)",
     "High"),
    ("AUTH-003", "Auth", "UI/Functional", "Login Form",
     "Login dengan email tidak valid (format)",
     "—",
     "1. Buka /login\n2. Isi 'bukan-email'\n3. Isi password\n4. Klik Masuk",
     "Validasi form gagal, error 'Format email tidak valid'",
     "Medium"),
    ("AUTH-004", "Auth", "UI/Functional", "Login Form",
     "Login dengan kredensial salah",
     "—",
     "1. Buka /login\n2. Email valid + password salah\n3. Klik Masuk",
     "Error toast, tetap di /login",
     "High"),
    ("AUTH-005", "Auth", "Integration", "JWT 401",
     "Auto-logout saat token expired (401)",
     "User login, token expired",
     "1. Login\n2. Modify localStorage access_token jadi invalid\n3. Refresh atau click link ke protected route",
     "Axios interceptor tangkap 401, clear token, redirect ke /login",
     "High"),
    ("AUTH-006", "Auth", "Security", "Middleware",
     "Akses protected route tanpa token",
     "User belum login",
     "1. Tanpa login, buka /dashboard",
     "Middleware redirect ke /login?redirect=/dashboard",
     "High"),
    ("AUTH-007", "Auth", "Security", "Middleware",
     "Student akses admin route",
     "Login sebagai student",
     "1. Login sebagai student\n2. Buka /dashboard-admin",
     "Middleware redirect ke /dashboard (role-based block)",
     "High"),
    ("AUTH-008", "Auth", "Security", "Middleware",
     "Teacher akses student route",
     "Login sebagai teacher",
     "1. Login sebagai teacher\n2. Buka /dashboard",
     "Middleware redirect ke /dashboard-admin",
     "High"),
    ("AUTH-009", "Auth", "Security", "JWT Decode",
     "JWT dengan role claim dimanipulasi",
     "—",
     "1. Decode JWT, ganti role 'student' ke 'admin'\n2. Set ke localStorage\n3. Buka /dashboard-admin",
     "Backend reject, 401, redirect ke /login",
     "High"),
    ("AUTH-010", "Auth", "UI/Functional", "Auth Pages",
     "Akses /login saat sudah login",
     "User sudah login",
     "1. Login\n2. Buka /login lagi",
     "Middleware redirect ke dashboard sesuai role",
     "Medium"),

    # Section B: CBT Engine (HIGHEST PRIORITY)
    ("CBT-001", "CBT", "UI/Functional", "Exam Intro",
     "Lihat halaman intro exam",
     "User punya upcoming exam",
     "1. Buka /cbt/check",
     "Tampil list upcoming exam dengan judul, waktu, tombol Mulai",
     "High"),
    ("CBT-002", "CBT", "Integration", "Exam Start",
     "Mulai exam baru",
     "User punya attempt yang valid",
     "1. Klik 'Mulai' di /cbt/check\n2. Pilih exam\n3. Konfirmasi",
     "POST /student/exams-access, redirect ke /cbt/exam, exam data loaded",
     "High"),
    ("CBT-003", "CBT", "UI/Functional", "Question Render",
     "Render soal single choice",
     "Exam dimulai",
     "1. Lihat soal pertama (tipe single_choice)",
     "Soal tampil dengan opsi A/B/C/D, radio button",
     "High"),
    ("CBT-004", "CBT", "UI/Functional", "Question Render",
     "Render soal multiple choice",
     "—",
     "1. Lihat soal multiple choice",
     "Soal tampil dengan checkbox untuk multiple selection",
     "High"),
    ("CBT-005", "CBT", "UI/Functional", "Question Render",
     "Render soal true/false",
     "—",
     "1. Lihat soal true/false",
     "Soal tampil dengan 2 opsi: Benar / Salah",
     "High"),
    ("CBT-006", "CBT", "UI/Functional", "Question Render",
     "Render soal matching (kiri-kanan)",
     "—",
     "1. Lihat soal matching",
     "Soal tampil dengan kolom kiri & kanan, bisa di-drag atau klik-pair",
     "High"),
    ("CBT-007", "CBT", "UI/Functional", "Question Render",
     "Render soal short_answer",
     "—",
     "1. Lihat soal short_answer",
     "Soal tampil dengan text input untuk jawaban",
     "High"),
    ("CBT-008", "CBT", "UI/Functional", "Question Render",
     "Render soal dengan image",
     "Soal punya image",
     "1. Lihat soal yang ada image-nya",
     "Image tampil dengan benar, dari Supabase CDN",
     "Medium"),
    ("CBT-009", "CBT", "UI/Functional", "Question Render",
     "Render math dengan KaTeX",
     "Soal ada formula matematika",
     "1. Lihat soal dengan formula matematika",
     "Formula ter-render dengan KaTeX (proper math symbols)",
     "Medium"),
    ("CBT-010", "CBT", "State", "Answer State",
     "Pilih jawaban untuk single choice",
     "Di exam view",
     "1. Klik opsi A di soal single choice",
     "Opsi A ter-select, state tersimpan di Redux exam slice",
     "High"),
    ("CBT-011", "CBT", "Integration", "Auto Save",
     "Auto-save jawaban ke server",
     "User memilih jawaban",
     "1. Pilih jawaban\n2. Tunggu 5 detik",
     "POST /student/exams-attempt/{id}/answers, toast 'Jawaban tersimpan'",
     "High"),
    ("CBT-012", "CBT", "Edge", "Auto Save",
     "Auto-save saat offline (network failure)",
     "Network down",
     "1. Pilih jawaban saat network down\n2. Tunggu auto-save attempt",
     "Save ke localStorage snapshot, retry saat network up",
     "High"),
    ("CBT-013", "CBT", "Critical", "Timer",
     "Timer countdown normal",
     "Exam baru mulai",
     "1. Mulai exam\n2. Biarkan timer jalan",
     "Timer countdown dari duration (misal 60:00 -> 59:59 -> ...)",
     "High"),
    ("CBT-014", "CBT", "Critical", "Timer",
     "Auto-submit saat timer habis",
     "Timer tinggal 0",
     "1. Tunggu timer habis",
     "Auto-submit exam, redirect ke /summary, no manual click needed",
     "High"),
    ("CBT-015", "CBT", "Critical", "Tab Switch",
     "Tab switch detection (1st time)",
     "User fullscreen exam",
     "1. Switch ke tab lain (Alt+Tab)\n2. Kembali ke exam tab",
     "Lives counter: 3 -> 2, warning popup 'Anda terdeteksi keluar tab'",
     "High"),
    ("CBT-016", "CBT", "Critical", "Tab Switch",
     "Tab switch 2nd time",
     "Sudah 1 lives hilang",
     "1. Switch tab lagi",
     "Lives: 2 -> 1, warning lebih tegas",
     "High"),
    ("CBT-017", "CBT", "Critical", "Tab Switch",
     "Tab switch 3rd time = disqualified",
     "Sudah 2 lives hilang",
     "1. Switch tab 3x",
     "Lives: 1 -> 0, exam auto-submit, status 'disqualified'",
     "High"),
    ("CBT-018", "CBT", "UI/Functional", "Fullscreen",
     "Fullscreen mode (useFullscreenGuard)",
     "Exam dimulai",
     "1. Exam dimulai",
     "Browser dalam fullscreen mode, ESC ditekan = warning + exit detection",
     "High"),
    ("CBT-019", "CBT", "UI/Functional", "Fullscreen",
     "Escape fullscreen detected",
     "User di fullscreen",
     "1. Tekan ESC",
     "useFullscreenGuard detect, warning + lives check",
     "High"),
    ("CBT-020", "CBT", "UI/Functional", "Navigation",
     "Navigasi next/prev question",
     "—",
     "1. Klik tombol 'Selanjutnya'\n2. Klik 'Sebelumnya'",
     "Pindah soal, currentQuestionIndex update",
     "High"),
    ("CBT-021", "CBT", "UI/Functional", "Navigation",
     "Skip question (tidak dijawab)",
     "—",
     "1. Klik Selanjutnya tanpa menjawab",
     "Soal ditandai 'unanswered', pindah ke soal berikutnya",
     "High"),
    ("CBT-022", "CBT", "UI/Functional", "Navigation",
     "Mark/flag question untuk review",
     "—",
     "1. Klik icon flag di soal",
     "Soal ditandai 'flagged', icon berubah warna",
     "High"),
    ("CBT-023", "CBT", "UI/Functional", "Navigation",
     "Jump ke soal tertentu dari question nav",
     "—",
     "1. Klik nomor soal di navigation panel",
     "Pindah ke soal tersebut, status soal visible (answered/unanswered/flagged)",
     "High"),
    ("CBT-024", "CBT", "UI/Functional", "Exam Summary",
     "Lihat summary sebelum submit",
     "Semua soal sudah dijawab/dilewati",
     "1. Klik 'Lihat Ringkasan'",
     "Tampil summary: total soal, dijawab, unanswered, flagged, tombol Submit",
     "High"),
    ("CBT-025", "CBT", "Integration", "Submit",
     "Submit exam manual",
     "—",
     "1. Di summary, klik 'Submit Final'",
     "POST /student/exams-attempt/{id}/submit, redirect ke result page",
     "High"),
    ("CBT-026", "CBT", "Integration", "Resume",
     "Resume exam setelah disconnect",
     "User exam masih in-progress",
     "1. Refresh page / tutup browser\n2. Buka /cbt/exam lagi",
     "Exam resume dari localStorage snapshot, jawaban tersimpan restored",
     "High"),
    ("CBT-027", "CBT", "UI/Functional", "Result",
     "Lihat hasil exam",
     "Exam sudah disubmit",
     "1. Setelah submit, redirect ke result",
     "Tampil: nilai, benar/salah, pembahasan (jika ada)",
     "High"),

    # Section C: Student / Dashboard
    ("STU-001", "Student", "UI/Functional", "Dashboard",
     "Lihat dashboard student",
     "Student login",
     "1. Buka /dashboard",
     "Tampil: upcoming exam, course yang diikuti, progress",
     "Medium"),
    ("STU-002", "Student", "UI/Functional", "Courses",
     "Browse semua course",
     "—",
     "1. Buka /courses",
     "Tampil list course dengan search, filter, pagination",
     "Medium"),
    ("STU-003", "Student", "UI/Functional", "Courses",
     "Search course by keyword",
     "—",
     "1. Buka /courses\n2. Ketik keyword di search",
     "List filter sesuai keyword",
     "Medium"),
    ("STU-004", "Student", "UI/Functional", "Courses",
     "View course detail & topic tree",
     "—",
     "1. Buka /courses/courseId",
     "Tampil: course info, daftar topic, progress bar",
     "High"),
    ("STU-005", "Student", "Integration", "Courses",
     "Enroll ke course",
     "—",
     "1. Buka course\n2. Klik 'Enroll'",
     "POST /student/enroll, status berubah 'enrolled'",
     "High"),
    ("STU-006", "Student", "UI/Functional", "Courses",
     "View content block (text/media/quiz)",
     "Student enrolled",
     "1. Buka course -> topic -> content",
     "Tampil sesuai tipe: text (rich), media (image/video), quiz",
     "High"),
    ("STU-007", "Student", "Integration", "Quiz",
     "Start quiz attempt",
     "—",
     "1. Buka content quiz\n2. Klik 'Mulai Quiz'",
     "POST /student/content/{id}/quiz/start, attempt_id dibuat",
     "High"),
    ("STU-008", "Student", "Integration", "Quiz",
     "Submit quiz",
     "—",
     "1. Jawab semua soal\n2. Klik Submit",
     "POST /student/quiz-attempts/{id}/submit, tampil result",
     "High"),
    ("STU-009", "Student", "UI/Functional", "Notes",
     "Create note per topic",
     "—",
     "1. Buka topic\n2. Klik 'Tambah Catatan'\n3. Isi note\n4. Save",
     "Note tersimpan, tampil di list",
     "Medium"),
    ("STU-010", "Student", "UI/Functional", "Notes",
     "Edit/delete note",
     "Note exists",
     "1. Klik edit/hapus di note",
     "Note ter-update atau terhapus",
     "Medium"),
    ("STU-011", "Student", "UI/Functional", "Notifications",
     "Lihat notifikasi",
     "—",
     "1. Klik icon bell",
     "Tampil list notifikasi (unread highlighted)",
     "Medium"),
    ("STU-012", "Student", "Integration", "Notifications",
     "Mark as read",
     "—",
     "1. Klik salah satu notifikasi",
     "POST /student/notifications/{id}/read, unread count decrement",
     "Medium"),
    ("STU-013", "Student", "UI/Functional", "Team",
     "Lihat detail team",
     "Student dalam team",
     "1. Buka /team",
     "Tampil info team, anggota, posisi leaderboard",
     "Medium"),
    ("STU-014", "Student", "UI/Functional", "Profile",
     "Edit profile student",
     "—",
     "1. Buka profile\n2. Edit data\n3. Save",
     "PUT /student/profile, data ter-update",
     "Low"),

    # Section D: Admin / Teacher
    ("ADM-001", "Admin", "UI/Functional", "Dashboard",
     "Lihat dashboard admin",
     "Teacher login",
     "1. Buka /dashboard-admin",
     "Tampil stats: total student, course, exam, revenue",
     "Medium"),
    ("ADM-002", "Admin", "UI/Functional", "Courses",
     "CRUD course (teacher)",
     "—",
     "1. Buka /dashboard-admin/courses\n2. Create/Edit/Delete course",
     "Course ter-CRUD, muncul di student course list",
     "High"),
    ("ADM-003", "Admin", "UI/Functional", "Topics",
     "CRUD topic per course",
     "—",
     "1. Buka course detail\n2. Tambah/edit/hapus topic",
     "Topic ter-CRUD",
     "High"),
    ("ADM-004", "Admin", "UI/Functional", "Content",
     "Add text content block",
     "—",
     "1. Buka topic\n2. Add content -> Text block",
     "POST /teacher/topics/{id}/content (type: text), muncul di student view",
     "High"),
    ("ADM-005", "Admin", "UI/Functional", "Content",
     "Add media content (image/video)",
     "—",
     "1. Add content -> Media\n2. Upload file",
     "Upload ke Supabase storage, content ter-link",
     "High"),
    ("ADM-006", "Admin", "UI/Functional", "Content",
     "Add quiz content",
     "—",
     "1. Add content -> Quiz\n2. Isi pertanyaan dengan Tiptap editor",
     "Quiz tersimpan dengan questions array",
     "High"),
    ("ADM-007", "Admin", "Integration", "Exam",
     "Create exam (teacher)",
     "—",
     "1. Buka course -> 'Tambah Ujian'\n2. Isi judul, duration, due date\n3. Save",
     "POST /teacher/courses/{id}/exam, exam dibuat",
     "High"),
    ("ADM-008", "Admin", "UI/Functional", "Exam",
     "Add questions to exam",
     "—",
     "1. Buka exam\n2. Add question (single/multiple/essay/matching)",
     "POST /teacher/exams/{id}/questions, question tersimpan",
     "High"),
    ("ADM-009", "Admin", "UI/Functional", "Exam",
     "Edit exam settings",
     "—",
     "1. Buka exam\n2. Edit title/duration/due date\n3. Save",
     "PUT /teacher/exams/{id}, exam updated",
     "High"),
    ("ADM-010", "Admin", "UI/Functional", "Exam Dashboard",
     "Lihat analytics exam",
     "—",
     "1. Buka exam -> 'Dashboard'",
     "Tampil: total attempts, avg score, distribution, top students",
     "High"),
    ("ADM-011", "Admin", "UI/Functional", "Cheating Report",
     "Lihat report cheating per exam",
     "—",
     "1. Buka /dashboard-admin/cheating-report\n2. Pilih exam",
     "Tampil list student dengan tab switch count, screenshots (jika ada)",
     "High"),
    ("ADM-012", "Admin", "UI/Functional", "Disqualified",
     "Lihat student yang didiskualifikasi",
     "—",
     "1. Buka /dashboard-admin/disqualified-participants",
     "Tampil list student disqualified + reason",
     "Medium"),
    ("ADM-013", "Admin", "UI/Functional", "Participants",
     "Lihat list participant",
     "—",
     "1. Buka /dashboard-admin/participant",
     "Tampil list student, status, progress",
     "High"),
    ("ADM-014", "Admin", "Integration", "Participants",
     "Bulk upload participant",
     "—",
     "1. Download template\n2. Isi data\n3. Upload file",
     "POST /teacher/add-participant/bulk, student ter-import",
     "High"),
    ("ADM-015", "Admin", "UI/Functional", "Participants",
     "Add single participant",
     "—",
     "1. Klik 'Tambah Peserta'\n2. Isi form\n3. Save",
     "POST /teacher/add-participant, student baru dibuat",
     "Medium"),
    ("ADM-016", "Admin", "UI/Functional", "Exam Results",
     "Lihat hasil exam per student",
     "—",
     "1. Buka exam -> Results",
     "Tampil list student + score + status",
     "High"),

    # Section E: Public / Landing
    ("PUB-001", "Public", "UI/Visual", "Landing",
     "Render landing page",
     "—",
     "1. Buka / (tanpa login)",
     "Landing tampil dengan hero, CTA, features",
     "Low"),
    ("PUB-002", "Public", "UI/Visual", "Produk",
     "Lihat halaman produk",
     "—",
     "1. Buka /produk",
     "Halaman produk tampil dengan deskripsi fitur",
     "Low"),
    ("PUB-003", "Public", "UI/Visual", "Tentang Kami",
     "Lihat about page",
     "—",
     "1. Buka /tentang-kami",
     "Halaman about tampil dengan visi-misi, team",
     "Low"),
]

# Format: (ID, Endpoint, Method, Tipe, Test Case, Pre-condition, Request, Expected, Priority)
API_TEST_CASES = [
    # Auth endpoints
    ("API-AUTH-001", "/auth/login-elearning", "POST", "Functional",
     "Login dengan kredensial valid",
     "User student terdaftar",
     '{"email": "student@test.com", "password": "Valid123!"}',
     '200 OK, response: {token, user: {id, email, RoleName: "student"}}',
     "High"),
    ("API-AUTH-002", "/auth/login-elearning", "POST", "Validation",
     "Login dengan format email salah",
     "—",
     '{"email": "invalid", "password": "abc"}',
     '400 Bad Request, errors.email',
     "Medium"),
    ("API-AUTH-003", "/auth/login-elearning", "POST", "Functional",
     "Login password salah",
     "—",
     '{"email": "student@test.com", "password": "wrong"}',
     '401 Unauthorized, message: "Invalid credentials"',
     "High"),
    ("API-AUTH-004", "/auth/login-elearning", "POST", "Security",
     "Rate limiting (5x salah)",
     "—",
     "5x POST dengan password salah dalam 5 menit",
     '429 Too Many Requests',
     "Medium"),
    ("API-AUTH-005", "/auth/me", "GET", "Functional",
     "Get current user",
     "User logged in",
     "(with valid token)",
     '200 OK, {id, email, RoleName, UserType, full_name}',
     "High"),
    ("API-AUTH-006", "/auth/me", "GET", "Security",
     "Get user tanpa token",
     "—",
     "(no token)",
     '401 Unauthorized',
     "High"),
    ("API-AUTH-007", "/auth/me", "GET", "Security",
     "Get user dengan token expired",
     "—",
     "(expired token)",
     '401 Unauthorized, message: "Token expired"',
     "High"),
    ("API-AUTH-008", "/auth/login-elearning", "POST", "Functional",
     "Login teacher",
     "Teacher terdaftar",
     '{"email": "teacher@test.com", "password": "Valid123!"}',
     '200 OK, role = "teacher"',
     "High"),

    # Student courses
    ("API-STU-001", "/courses/browse", "GET", "Functional",
     "Browse course publik",
     "—",
     "?page=1&per_page=10&search=matematika",
     '200 OK, list course with pagination',
     "Medium"),
    ("API-STU-002", "/student/courses", "GET", "Functional",
     "Get my enrolled courses",
     "Student login",
     "(with valid token)",
     '200 OK, list course yang di-enroll',
     "High"),
    ("API-STU-003", "/student/enroll", "POST", "Functional",
     "Enroll ke course",
     "—",
     '{"course_id": 1}',
     '201 Created, status enrolled',
     "High"),
    ("API-STU-004", "/student/enroll", "POST", "Edge",
     "Enroll ke course yang sudah di-enroll",
     "—",
     '{"course_id": 1}',
     '409 Conflict, "Already enrolled"',
     "Medium"),
    ("API-STU-005", "/student/courses/:id", "GET", "Functional",
     "Get course detail",
     "—",
     "/student/courses/1",
     '200 OK, course detail dengan topics',
     "High"),
    ("API-STU-006", "/student/courses/:id/topics", "GET", "Functional",
     "Get topics per course",
     "—",
     "/student/courses/1/topics",
     '200 OK, list topics',
     "High"),
    ("API-STU-007", "/student/content/:id", "GET", "Functional",
     "Get content detail",
     "—",
     "/student/content/123",
     '200 OK, content (text/media/quiz)',
     "High"),
    ("API-STU-008", "/student/content/:id/complete", "POST", "Integration",
     "Mark content complete",
     "—",
     "(no body)",
     '200 OK, progress updated',
     "Medium"),
    ("API-STU-009", "/student/content/:id/incomplete", "POST", "Integration",
     "Mark content incomplete",
     "—",
     "(no body)",
     '200 OK, progress reset',
     "Low"),

    # Quiz
    ("API-QUIZ-001", "/student/content/:id/quiz/start", "POST", "Functional",
     "Start quiz attempt",
     "—",
     "(no body)",
     '201 Created, response: {attempt_id, questions}',
     "High"),
    ("API-QUIZ-002", "/student/quiz-attempts/:id/answers", "POST", "Functional",
     "Submit quiz answer",
     "—",
     '{"question_id": "q1", "selected_option_id": ["opt1"]}',
     '200 OK, answer saved',
     "High"),
    ("API-QUIZ-003", "/student/quiz-attempts/:id/submit", "POST", "Functional",
     "Submit final quiz",
     "—",
     "(no body)",
     '200 OK, response: {score, status: "submitted"}',
     "High"),
    ("API-QUIZ-004", "/student/quiz-attempts/:id/result", "GET", "Functional",
     "Get quiz result",
     "—",
     "/student/quiz-attempts/123/result",
     '200 OK, score + detail per question',
     "High"),

    # Notes
    ("API-NOTE-001", "/student/topics/:id/notes", "GET", "Functional",
     "List notes per topic",
     "—",
     "/student/topics/1/notes",
     '200 OK, list notes user',
     "Medium"),
    ("API-NOTE-002", "/student/notes", "POST", "Functional",
     "Create note",
     "—",
     '{"topic_id": 1, "content": "catatan saya"}',
     '201 Created, note saved',
     "Medium"),
    ("API-NOTE-003", "/student/notes/:id", "PUT", "Functional",
     "Update note",
     "—",
     '{"content": "updated"}',
     '200 OK',
     "Medium"),
    ("API-NOTE-004", "/student/notes/:id", "DELETE", "Functional",
     "Delete note",
     "—",
     "(no body)",
     '200 OK, soft delete',
     "Medium"),

    # CBT (CRITICAL)
    ("API-CBT-001", "/upcoming-exam", "GET", "Functional",
     "Get upcoming exams for student",
     "Student login",
     "(with valid token)",
     '200 OK, list exam dengan date, subject, duration',
     "High"),
    ("API-CBT-002", "/student/exams/access", "POST", "Functional",
     "Access exam (create attempt)",
     "—",
     '{"exam_id": 1}',
     '201 Created, attempt_id, exam data',
     "High"),
    ("API-CBT-003", "/student/exams-attempt/:id/answers", "POST", "Critical",
     "Save exam answer (auto-save)",
     "Exam in progress",
     '{"question_id": "q1", "selected_option_id": ["opt1"]}',
     '200 OK, answer persisted',
     "High"),
    ("API-CBT-004", "/student/exams-attempt/:id/tab-switch", "POST", "Critical",
     "Record tab switch (lives)",
     "User switch tab",
     '{"timestamp": "2026-06-22T10:00:00Z"}',
     '200 OK, {lives_remaining, warning_message, is_disqualified}',
     "High"),
    ("API-CBT-005", "/student/exams-attempt/:id/tab-switch", "POST", "Critical",
     "Tab switch ke-3 = disqualify",
     "Sudah 2 tab switches",
     '{"timestamp": "2026-06-22T10:05:00Z"}',
     '200 OK, is_disqualified: true, exam auto-submit',
     "High"),
    ("API-CBT-006", "/student/exams-attempt/:id/submit", "POST", "Critical",
     "Submit exam final",
     "—",
     "(no body)",
     '200 OK, exam graded, attempt status submitted',
     "High"),
    ("API-CBT-007", "/student/exams-attempt/:id/questions/:qid", "DELETE", "Functional",
     "Clear answer",
     "—",
     "(no body)",
     '200 OK, answer cleared',
     "Medium"),
    ("API-CBT-008", "/student/exams-attempt/:id", "GET", "Functional",
     "Get current attempt state",
     "—",
     "(no body)",
     '200 OK, full attempt data untuk resume',
     "High"),
    ("API-CBT-009", "/student/exams-attempt/:id/submit", "POST", "Edge",
     "Submit exam yang sudah disubmit",
     "—",
     "(no body)",
     '409 Conflict, "Exam already submitted"',
     "Medium"),

    # Notifications
    ("API-NOTIF-001", "/student/notifications", "GET", "Functional",
     "List notifications",
     "—",
     "?page=1&per_page=20",
     '200 OK, list notifications',
     "Medium"),
    ("API-NOTIF-002", "/student/notifications/unread-count", "GET", "Functional",
     "Get unread count",
     "—",
     "(no params)",
     '200 OK, {unread_count: 5}',
     "Medium"),
    ("API-NOTIF-003", "/student/notifications/:id/read", "POST", "Functional",
     "Mark as read",
     "—",
     "(no body)",
     '200 OK',
     "Medium"),
    ("API-NOTIF-004", "/student/notifications/read-all", "POST", "Functional",
     "Mark all as read",
     "—",
     "(no body)",
     '200 OK',
     "Medium"),
    ("API-NOTIF-005", "/student/notifications/:id", "DELETE", "Functional",
     "Delete notification",
     "—",
     "(no body)",
     '200 OK',
     "Medium"),
    ("API-NOTIF-006", "/student/notifications", "DELETE", "Functional",
     "Delete all notifications",
     "—",
     "(no body)",
     '200 OK',
     "Medium"),

    # Teacher courses
    ("API-TCH-001", "/teacher/courses", "GET", "Functional",
     "List teacher courses",
     "Teacher login",
     "(with valid token)",
     '200 OK, list course yang diajar',
     "High"),
    ("API-TCH-002", "/teacher/add-course", "POST", "Functional",
     "Create new course",
     "—",
     '{"title": "...", "description": "...", "subject": "math"}',
     '201 Created, course_id',
     "High"),
    ("API-TCH-003", "/teacher/courses/:id", "PUT", "Functional",
     "Update course",
     "—",
     '{"title": "Updated"}',
     '200 OK',
     "High"),
    ("API-TCH-004", "/teacher/courses/:id", "DELETE", "Functional",
     "Delete course",
     "—",
     "(no body)",
     '200 OK, soft delete',
     "High"),
    ("API-TCH-005", "/teacher/courses/:id/topics", "POST", "Functional",
     "Add topic to course",
     "—",
     '{"title": "Aljabar", "order": 1}',
     '201 Created',
     "High"),
    ("API-TCH-006", "/teacher/topics/:id", "PUT", "Functional",
     "Update topic",
     "—",
     '{"title": "Updated"}',
     '200 OK',
     "Medium"),
    ("API-TCH-007", "/teacher/topics/:id", "DELETE", "Functional",
     "Delete topic",
     "—",
     "(no body)",
     '200 OK',
     "Medium"),
    ("API-TCH-008", "/teacher/topics/:id/content", "POST", "Functional",
     "Add content to topic",
     "—",
     '{"type": "text", "title": "...", "body": "..."}',
     '201 Created, content_id',
     "High"),

    # Teacher exams
    ("API-EXM-001", "/teacher/exams", "GET", "Functional",
     "List all teacher exams",
     "—",
     "(with valid token)",
     '200 OK, list exam',
     "High"),
    ("API-EXM-002", "/teacher/courses/:id/exam", "POST", "Functional",
     "Create exam for course",
     "—",
     '{"title": "UTS", "duration": 60, "due_date": "2026-12-31"}',
     '201 Created, exam_id',
     "High"),
    ("API-EXM-003", "/teacher/exams/:id", "PUT", "Functional",
     "Update exam",
     "—",
     '{"title": "Updated"}',
     '200 OK',
     "High"),
    ("API-EXM-004", "/teacher/exams/:id", "DELETE", "Functional",
     "Delete exam",
     "—",
     "(no body)",
     '200 OK',
     "High"),
    ("API-EXM-005", "/teacher/exams/:id/questions", "POST", "Functional",
     "Add question to exam",
     "—",
     '{"question_text": "...", "question_type": "single", "options": [...], "correct": "a"}',
     '201 Created',
     "High"),
    ("API-EXM-006", "/teacher/exams/:id/dashboard", "GET", "Functional",
     "Exam analytics dashboard",
     "—",
     "/teacher/exams/123/dashboard",
     '200 OK, {total_attempts, avg_score, distribution}',
     "High"),
    ("API-EXM-007", "/teacher/exams/:id/cheating", "GET", "Functional",
     "Cheating report",
     "—",
     "/teacher/exams/123/cheating",
     '200 OK, list tab switches per student',
     "High"),
    ("API-EXM-008", "/teacher/exams/:id/disqualified", "GET", "Functional",
     "Disqualified participants",
     "—",
     "/teacher/exams/123/disqualified",
     '200 OK, list disqualified students',
     "High"),
    ("API-EXM-009", "/teacher/exams/:id/participants", "GET", "Functional",
     "Exam participants list",
     "—",
     "/teacher/exams/123/participants",
     '200 OK, list students yang ikut',
     "High"),
    ("API-EXM-010", "/teacher/exams/:id/results", "GET", "Functional",
     "Exam results per student",
     "—",
     "/teacher/exams/123/results",
     '200 OK, list score per student',
     "High"),

    # Teacher participants
    ("API-PART-001", "/teacher/participants", "GET", "Functional",
     "List all participants",
     "—",
     "(with valid token)",
     '200 OK, list student',
     "High"),
    ("API-PART-002", "/teacher/participants/template", "GET", "Functional",
     "Download template bulk upload",
     "—",
     "(no params)",
     '200 OK, file CSV/XLSX',
     "Medium"),
    ("API-PART-003", "/teacher/add-participant/bulk", "POST", "Integration",
     "Bulk upload participants",
     "—",
     "multipart: file=@participants.csv",
     '200 OK, {imported: 50, errors: []}',
     "High"),
    ("API-PART-004", "/teacher/add-participant", "POST", "Functional",
     "Add single participant",
     "—",
     '{"name": "...", "email": "...", "team_id": 1}',
     '201 Created',
     "Medium"),
    ("API-PART-005", "/teacher/elearning-user/:id", "DELETE", "Functional",
     "Delete participant",
     "—",
     "(no body)",
     '200 OK',
     "Medium"),

    # Team
    ("API-TEAM-001", "/elearning/team-details", "GET", "Functional",
     "Get my team details",
     "—",
     "(with valid token)",
     '200 OK, {id, name, members: [...], score}',
     "Medium"),
    ("API-TEAM-002", "/teams", "GET", "Functional",
     "List all teams (leaderboard)",
     "—",
     "(no params)",
     '200 OK, list teams sorted by score',
     "Medium"),
]

# Generate XLSX
wb = Workbook()
wb.remove(wb.active)

# Sheet 1: Test Cases (UI)
ws1 = wb.create_sheet("Test Cases")
headers1 = ["ID", "Modul", "Tipe", "Item", "Test Case", "Pre-condition", "Steps", "Expected Result", "Priority", "Status", "Actual Result", "Catatan"]
ws1.append(headers1)

for tc in TEST_CASES:
    row = list(tc) + ["Belum Dieksekusi", "", ""]
    ws1.append(row)

for col in range(1, len(headers1) + 1):
    cell = ws1.cell(row=1, column=col)
    cell.font = HEADER_FONT
    cell.fill = HEADER_FILL
    cell.alignment = HEADER_ALIGN
    cell.border = BORDER

for row_idx in range(2, len(TEST_CASES) + 2):
    for col_idx in range(1, len(headers1) + 1):
        cell = ws1.cell(row=row_idx, column=col_idx)
        cell.font = DATA_FONT
        cell.alignment = DATA_ALIGN
        cell.border = BORDER
    priority = ws1.cell(row=row_idx, column=9).value
    if priority == "High":
        ws1.cell(row=row_idx, column=9).fill = PRIORITY_HIGH
    elif priority == "Medium":
        ws1.cell(row=row_idx, column=9).fill = PRIORITY_MED
    elif priority == "Low":
        ws1.cell(row=row_idx, column=9).fill = PRIORITY_LOW

col_widths1 = [12, 12, 18, 22, 40, 30, 50, 50, 10, 16, 30, 25]
for i, w in enumerate(col_widths1, start=1):
    ws1.column_dimensions[get_column_letter(i)].width = w
ws1.row_dimensions[1].height = 30
ws1.freeze_panes = "A2"
ws1.auto_filter.ref = f"A1:{get_column_letter(len(headers1))}{len(TEST_CASES) + 1}"

# Sheet 2: API Test Cases
ws2 = wb.create_sheet("API Test Cases")
headers2 = ["ID", "Endpoint", "Method", "Tipe", "Test Case", "Pre-condition", "Request Body / Params", "Expected Response", "Priority", "Status", "Actual Result", "Catatan"]
ws2.append(headers2)

for tc in API_TEST_CASES:
    row = list(tc) + ["Belum Dieksekusi", "", ""]
    ws2.append(row)

for col in range(1, len(headers2) + 1):
    cell = ws2.cell(row=1, column=col)
    cell.font = HEADER_FONT
    cell.fill = HEADER_FILL
    cell.alignment = HEADER_ALIGN
    cell.border = BORDER

for row_idx in range(2, len(API_TEST_CASES) + 2):
    for col_idx in range(1, len(headers2) + 1):
        cell = ws2.cell(row=row_idx, column=col_idx)
        cell.font = DATA_FONT
        cell.alignment = DATA_ALIGN
        cell.border = BORDER
    priority = ws2.cell(row=row_idx, column=9).value
    if priority == "High":
        ws2.cell(row=row_idx, column=9).fill = PRIORITY_HIGH
    elif priority == "Medium":
        ws2.cell(row=row_idx, column=9).fill = PRIORITY_MED
    elif priority == "Low":
        ws2.cell(row=row_idx, column=9).fill = PRIORITY_LOW

col_widths2 = [14, 28, 8, 18, 40, 30, 40, 50, 10, 16, 30, 25]
for i, w in enumerate(col_widths2, start=1):
    ws2.column_dimensions[get_column_letter(i)].width = w
ws2.row_dimensions[1].height = 30
ws2.freeze_panes = "A2"
ws2.auto_filter.ref = f"A1:{get_column_letter(len(headers2))}{len(API_TEST_CASES) + 1}"

# Sheet 3: Summary
ws3 = wb.create_sheet("Summary", 0)
ws3.append(["Arteri E-Learning (Stuudi) - Test Case Summary"])
ws3.append([])
ws3.append(["Document Info", ""])
ws3.append(["Project", "Arteri E-Learning Platform (Stuudi)"])
ws3.append(["Frontend Repo", "github.com/irzadzulhika29/stuudi-frontend"])
ws3.append(["Backend Repo", "github.com/azmiagr/lms-project (out of scope)"])
ws3.append(["Live URL", "https://stuudi.vercel.app"])
ws3.append(["Test Plan", "test-plan.md (BINUS framework, 19 sections)"])
ws3.append(["Generated", "2026-06-22"])
ws3.append([])
ws3.append(["Test Inventory", "Count"])
ws3.append(["UI Test Cases", len(TEST_CASES)])
ws3.append(["API Test Cases", len(API_TEST_CASES)])
ws3.append(["Total", len(TEST_CASES) + len(API_TEST_CASES)])
ws3.append([])

ws3.append(["By Modul (UI)", "Count"])
modul_count = {}
for tc in TEST_CASES:
    modul = tc[1]
    modul_count[modul] = modul_count.get(modul, 0) + 1
for modul, count in sorted(modul_count.items()):
    ws3.append([f"  {modul}", count])

ws3.append([])

ws3.append(["By Priority (UI)", "Count"])
prio_count = {"High": 0, "Medium": 0, "Low": 0}
for tc in TEST_CASES:
    prio_count[tc[8]] = prio_count.get(tc[8], 0) + 1
for prio, count in prio_count.items():
    ws3.append([f"  {prio}", count])

ws3.append([])

ws3.append(["By Endpoint (API)", "Count"])
ep_count = {}
for tc in API_TEST_CASES:
    endpoint = tc[1].split("/")[1] if "/" in tc[1] else tc[1]
    ep_count[endpoint] = ep_count.get(endpoint, 0) + 1
for ep, count in sorted(ep_count.items()):
    ws3.append([f"  /{ep}", count])

ws3.cell(row=1, column=1).font = Font(size=14, bold=True, color="1E40AF")
ws3.cell(row=1, column=1).fill = PatternFill("solid", fgColor="DBEAFE")

for r in [3, 10, 17, 24]:
    cell = ws3.cell(row=r, column=1)
    cell.font = Font(bold=True, color="1E40AF")

ws3.column_dimensions["A"].width = 30
ws3.column_dimensions["B"].width = 15

wb.save(OUTPUT)
size = os.path.getsize(OUTPUT)
print(f"OK XLSX saved: {OUTPUT}")
print(f"  Size: {size:,} bytes ({size/1024:.1f} KB)")
print(f"  Sheets: 3 (Summary, Test Cases, API Test Cases)")
print(f"  Test Cases (UI): {len(TEST_CASES)}")
print(f"  Test Cases (API): {len(API_TEST_CASES)}")
print(f"  Total: {len(TEST_CASES) + len(API_TEST_CASES)}")
